### PR TITLE
Loom provider flexible Eth methods

### PR DESCRIPTION
**Pull request by eduardonunesp**
* Adding more flexible eth methods, now is possible to add methods that
aren't provided also to overwrite default methods

### CODE REVIEW

**Comment by eduardonunesp** [comment]
For let the users `customize` or add calls on `loom-js`, for instance the `eth_getBalance` isn't supported, and `truffle v5` doesn't work without it.

```// Mocking eth_getBalance, since LoomProvider don't provides by defualt
loomTruffleProvider
  .getProviderEngine()
  .addCustomMethod('eth_getBalance', () => '0x10000000000000000000')```

**Comment by eduardonunesp** [comment]
Yeh, maybe, but what `eth_getBalance` will return if `Loom` do not cost Ether in order to deploy or call any EVM call on DAppChain.

**Comment by enlight** [comment]
It should probably either return zero (though I suspect this won't work), or a sufficiently large number to deploy/call anything.

**Comment by eduardonunesp** [comment]
Yeah, I believe `0x0` can be an option, or maybe throw a different error saying about the `overwriteMethod` option

**Comment by enlight** [comment]
It should work by default, it shouldn't throw an error.

**Comment by eduardonunesp** [comment]
`eth_getBalance` returning `0x0` by default, also added documentation for `add` and `overwrite` methods

**Pull request merged**
